name: flutter_lottie
description: A Dart based Lottie rendering library for Flutter.
version: 0.3.0
author: Dan Field <dfield@google.com>
homepage: https://github.com/dnfield/flutter_lottie

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  meta: ^1.1.6
  vector_math: ^2.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
